# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module RandomUserMeApi
  class StructuredPicture < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :large

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :medium

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :thumbnail

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["large"] = "large"
        @hash["medium"] = "medium"
        @hash["thumbnail"] = "thumbnail"
      end
      @hash
    end

    def initialize(large = nil,
                   medium = nil,
                   thumbnail = nil)
      @large = large
      @medium = medium
      @thumbnail = thumbnail
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        large = hash["large"]
        medium = hash["medium"]
        thumbnail = hash["thumbnail"]

        # Create object from extracted values
        StructuredPicture.new(large,
                              medium,
                              thumbnail)
      end
    end
  end
end
