# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module RandomUserMeApi

  class Configuration
    # The base Uri for API calls
    @base_uri = 'http://api.randomuser.me'

    # The attribute accessors for public properties
    class << self
      attr_accessor :base_uri
    end
 
  end
end
