# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module RandomUserMeApi
  class RandomUserMeAPIClient
    # Singleton access to user controller
    # @return [UserController] Returns the controller instance
    def user
      UserController.instance
    end

  end
end
